// packages/react/ds-app/src/lib/SideNavigation/common/NavTree/NavTree.tsx
import { useNavigationTree } from "@canonical/react-hooks";
import { getItemId } from "@canonical/utils";
import type React from "react";
import { useEffect } from "react";
import type { NavItem } from "../../types.js";
import { Item } from "../Item/index.js";
import type { NavTreeProps } from "./types.js";
import "./styles.css";

/**
 * Internal: renders a navigation tree with two explicit loops (no recursion),
 * deriving active state from useNavigationTree. Shared by Content and Footer —
 * each region drives its own hook instance over its own root.
 *
 *   Loop 1 — level-1 groups: each direct child of the root is a group; its
 *     label renders as a header (omitted when absent), wrapping its items.
 *   Loop 2 — level-2 items: each child of a group maps to a (flat) Item.
 *
 * The hook is generic over NavItem, so `icon`/`slot` survive typed onto the
 * annotated nodes. `currentUrl` seeds initial selection and re-syncs it on
 * navigation (the hook's `initialUrl` is mount-only), so the active item stays
 * in sync with the consumer's router.
 */
const NavTree = ({
  root,
  currentUrl,
  LinkComponent = "a",
}: NavTreeProps): React.ReactElement => {
  const nav = useNavigationTree<NavItem>({ root, initialUrl: currentUrl });
  const { index, selectItem } = nav;

  useEffect(() => {
    if (currentUrl === undefined) return;
    const match = index[currentUrl];
    if (match) selectItem(match);
  }, [currentUrl, index, selectItem]);

  const groups = nav.annotatedRoot.items ?? [];

  return (
    <div className="ds nav-tree">
      {/* Loop 1 — level-1 groups */}
      {groups.map((group) => {
        const groupId = getItemId(group);
        const items = group.items ?? [];
        return (
          <section className="group" key={groupId} data-depth={group.depth}>
            {group.label ? (
              <span className="header p">{group.label}</span>
            ) : null}
            <ul className="list">
              {/* Loop 2 — level-2 items */}
              {items.map((item) => (
                <Item
                  key={getItemId(item)}
                  {...item}
                  active={nav.getNodeStatus(item).selected}
                  LinkComponent={LinkComponent}
                />
              ))}
            </ul>
          </section>
        );
      })}
    </div>
  );
};

export default NavTree;

// packages/svelte/ds-app-wpe/src/lib/components/SideNavigation/common/NavTree/NavTree.svelte
<script lang="ts">
  import { findAncestorPath, getItemId } from "@canonical/utils";
  import { SvelteSet } from "svelte/reactivity";
  import { Item } from "../Item/index.js";
  import { setNavTreeContext } from "./context.js";
  import type { NavTreeProps } from "./types.js";
  import { useNavTree } from "./useNavTree.svelte.js";
  import "./styles.css";

  let { root, currentUrl }: NavTreeProps = $props();

  const tree = useNavTree({ root: () => root });
  const groups = $derived(tree.annotatedRoot.items ?? []);

  // Ids of expanded (disclosed) items, shared by every Item in this tree.
  const expandedIds = new SvelteSet<string>();

  // Shared with every Item beneath this tree via context — see
  // `common/NavTree/context.ts` — instead of threading tree/expandedIds/
  // currentUrl through each level of Item's own recursion.
  setNavTreeContext({ tree, expandedIds, currentUrl: () => currentUrl });

  // Reveal the active item: whenever currentUrl resolves to an item, open its
  // expandable ancestors. Only ever ADDS ids, so it never re-collapses a
  // group the user opened or closed by hand.
  $effect(() => {
    if (currentUrl === undefined) return;
    const match = tree.index[currentUrl];
    if (!match) return;
    for (const ancestor of findAncestorPath(tree.index, match)) {
      if (ancestor.depth >= 2 && ancestor.items?.length) {
        expandedIds.add(getItemId(ancestor));
      }
    }
  });
</script>

<div class="ds nav-tree">
  {#each groups as group (getItemId(group))}
    <section class="group">
      {#if group.label}
        <span class="header p">{group.label}</span>
      {/if}
      <ul class="list">
        {#each group.items ?? [] as item (getItemId(item))}
          <Item {item} />
        {/each}
      </ul>
    </section>
  {/each}
</div>

<!-- @component
Internal: renders a navigation tree from a root NavItem (its direct children
are groups; each group's items are the rendered rows). Shared by
`SideNavigation.Content` and `SideNavigation.Footer` — each region drives its
own `useNavTree` instance, so they're independent keyboard/focus domains.
-->
