// packages/react/ds-global/src/lib/Card/Card.tsx
/* @canonical/generator-ds 0.10.0-experimental.2 */

import type React from "react";
import { Content, Header, Image, Thumbnail } from "./common/index.js";
import type { CardProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds card";

/**
 * The card component is a rigid, repeatable container used to represent
 * specific data objects within a collection. Unlike the flexible Tile, a
 * card follows a strict internal structure to ensure that when multiple
 * cards are displayed together, the user can scan and compare attributes
 * across the set with minimal cognitive effort.
 *
 * @implements ds:global.component.card
 */
const Card = ({
  className,
  children,
  emphasis = "neutral",
  ...props
}: CardProps): React.ReactElement => (
  <div
    className={[componentCssClassName, emphasis, className]
      .filter(Boolean)
      .join(" ")}
    {...props}
  >
    {children}
  </div>
);

Card.Content = Content;
Card.Header = Header;
Card.Image = Image;
Card.Thumbnail = Thumbnail;

export default Card;

// packages/svelte/ds-app-wpe/src/lib/components/Card/Card.svelte
<script lang="ts">
  import type { CardProps } from "./types.js";
  import "./styles.css";

  const componentCssClassName = "ds card";

  let { children, class: className, ...rest }: CardProps = $props();
</script>

<div class={[componentCssClassName, className]} {...rest}>
  {@render children?.()}
</div>

<!-- @component
The `Card` component is a container designed to represent data objects that share
the same structure. Unlike the more flexible Tile, a card is designed to have
multiple units displayed beside one another, with a predictable structure that
allows the user to compare attributes across data objects.

A Card is always a grid participant: it is a ROW SUBGRID spanning four fixed
section tracks (image / header / content / footer), inheriting them from its
parent grid. Use inside a `Cards` group to align sections across a row.

`import { Card } from "@canonical/svelte-ds-app-wpe";`

## Example Usage
```svelte
<Card>
  <Card.Content>
    <h4>Card title</h4>
    <p>Card body text.</p>
  </Card.Content>
</Card>
```

@implements ds:global.component.card
-->
