// packages/svelte/ds-app-wpe/src/lib/components/Card/common/Header/Header.svelte
<script lang="ts">
  import type { HeaderProps } from "./types.js";
  import "./styles.css";

  const componentCssClassName = "ds card-header";

  let { children, class: className, ...rest }: HeaderProps = $props();
</script>

<div class={[componentCssClassName, className]} {...rest}>
  {@render children()}
</div>

// packages/react/ds-global/src/lib/Card/common/Header/Header.tsx
import type React from "react";
import type { HeaderProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds card-header";

/**
 * Header component for Card
 *
 * @implements ds:global.subcomponent.card-header
 */
const Header = ({
  children,
  className,
  ...props
}: HeaderProps): React.ReactElement => {
  return (
    <div
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
    >
      {children}
    </div>
  );
};

Header.displayName = "Card.Header";

export default Header;
