// packages/svelte/ds-app-wpe/src/lib/components/SideNavigation/common/Footer/Footer.svelte
<script lang="ts">
  import { NavTree } from "../NavTree/index.js";
  import type { FooterProps } from "./types.js";
  import "./styles.css";

  const componentCssClassName = "ds footer";

  let { root, currentUrl, class: className, ...rest }: FooterProps = $props();
</script>

<div class={[componentCssClassName, className]} {...rest}>
  <NavTree {root} {currentUrl} />
</div>

<!-- @component
`SideNavigation.Footer` — optional region pinned to the bottom, for
account-level or global actions. Drives its own `NavTree` over its `root`,
independent of Content. Stays visible (icon-only) while the rail is
collapsed — see the root `styles.css` for the collapsed-state label fade.
-->

// packages/react/ds-app/src/lib/SideNavigation/common/Footer/Footer.tsx
import type React from "react";
import { NavTree } from "../NavTree/index.js";
import type { FooterProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds footer";

/**
 * SideNavigation.Footer — optional region pinned to the bottom, holding
 * account-level or global actions. Drives its own useNavigationTree over its
 * `root` (independent of Content). Falls back to `children` when no `root`.
 *
 * @implements ds:apps.subcomponent.side-navigation-footer
 */
const Footer = ({
  className,
  root,
  LinkComponent = "a",
  currentUrl,
  children,
  ...props
}: FooterProps): React.ReactElement => {
  return (
    <div
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
    >
      {root ? (
        <NavTree
          root={root}
          currentUrl={currentUrl}
          LinkComponent={LinkComponent}
        />
      ) : (
        children
      )}
    </div>
  );
};

export default Footer;
