// packages/svelte/ds-app-launchpad/src/lib/components/Timeline/common/Event/Event.svelte
<!-- @canonical/generator-ds 0.10.0-experimental.2 -->

<script lang="ts">
  import { UserAvatar } from "../../../UserAvatar/index.js";
  import type { EventProps } from "./types.js";
  import "./styles.css";

  const componentCssClassName = "ds timeline-event";

  let {
    class: className,
    children,
    marker,
    markerSize = "small",
    titleRow,
    ...rest
  }: EventProps = $props();
</script>

<li
  class={[
    componentCssClassName,
    className,
    marker
      ? markerSize === "small"
        ? "marker-small"
        : "marker-large"
      : "marker-empty",
    { "with-title-row": titleRow },
  ]}
  {...rest}
>
  <div class="marker" aria-hidden="true">
    {#if typeof marker === "function"}
      {@render marker()}
    {:else if marker}
      <UserAvatar {...marker} />
    {/if}
  </div>
  {#if children || titleRow}
    <div class="content">
      {#if titleRow}
        <div class="title-row">
          {@render titleRow?.()}
        </div>
      {/if}
      {#if children}
        <div>
          {@render children()}
        </div>
      {/if}
    </div>
  {/if}
</li>

// packages/react/ds-global/src/lib/Timeline/common/Event/Event.tsx
import type React from "react";
import type { EventProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds timeline-event";

/**
 * Timeline.Event subcomponent
 *
 * A single event in the timeline, with optional actor and datetime.
 * DOM order per DSL: [0] actor, [1] datetime, [2] payload
 *
 * @implements ds:global.subcomponent.timeline-event
 */
const Event = ({
  actor,
  datetime,
  children,
  criticality,
  className,
  ...props
}: EventProps): React.ReactElement => (
  <div
    className={[componentCssClassName, criticality, className]
      .filter(Boolean)
      .join(" ")}
    {...props}
  >
    {/* Timeline marker/dot */}
    <div className="timeline-event-marker" aria-hidden="true" />

    {/* Event content container */}
    <div className="timeline-event-content">
      {/* edges[0]: actor (cardinality: 0..1) */}
      {actor && <div className="timeline-event-actor">{actor}</div>}

      {/* edges[1]: datetime (cardinality: 0..1) */}
      {datetime && <time className="timeline-event-datetime">{datetime}</time>}

      {/* edges[2]: payload (cardinality: 1, slotName: default) */}
      <div className="timeline-event-payload">{children}</div>
    </div>
  </div>
);

Event.displayName = "Timeline.Event";

export default Event;
