// packages/svelte/ds-app-launchpad/src/lib/components/common/DialogContent/common/Footer/Footer.svelte
<!-- @canonical/generator-ds 0.10.0-experimental.2 -->

<script lang="ts">
  import type { FooterProps } from "./types.js";
  import "./styles.css";

  const componentCssClassName = "ds dialog-content-footer";

  let { class: className, children, ...rest }: FooterProps = $props();
</script>

<footer class={[componentCssClassName, className]} {...rest}>
  {@render children?.()}
</footer>

// packages/react/ds-global/src/lib/component/Card/common/Footer/Footer.tsx
import type React from "react";
import type { FooterProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds card-footer";

/**
 * Footer component for Card. A padded content-bearing section pinned to the
 * bottom of the card, for tags and labels.
 *
 * @implements ds:global.subcomponent.card-footer
 */
const Footer = ({
  children,
  className,
  ...props
}: FooterProps): React.ReactElement => {
  return (
    <div
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
    >
      {children}
    </div>
  );
};

Footer.displayName = "Card.Footer";

export default Footer;
