// packages/react/ds-global/src/lib/Card/common/Content/Content.tsx
import type React from "react";
import type { ContentProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds card-content";

/**
 * Content component for Card
 *
 * @implements ds:global.subcomponent.card-content
 */
const Content = ({
  children,
  className,
  ...props
}: ContentProps): React.ReactElement => {
  return (
    <div
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
    >
      {children}
    </div>
  );
};

Content.displayName = "Card.Content";

export default Content;

// packages/svelte/ds-app-wpe/src/lib/components/Card/common/Content/Content.svelte
<script lang="ts">
  import type { ContentProps } from "./types.js";
  import "./styles.css";

  const componentCssClassName = "ds card-content";

  let { children, class: className, ...rest }: ContentProps = $props();
</script>

<div class={[componentCssClassName, className]} {...rest}>
  {@render children()}
</div>
