// packages/svelte/ds-app-wpe/src/lib/components/SideNavigation/common/Content/Content.svelte
<script lang="ts">
  import { NavTree } from "../NavTree/index.js";
  import type { ContentProps } from "./types.js";
  import "./styles.css";

  const componentCssClassName = "ds content";

  let { root, currentUrl, class: className, ...rest }: ContentProps = $props();
</script>

<div class={[componentCssClassName, className]} {...rest}>
  <NavTree {root} {currentUrl} />
</div>

<!-- @component
`SideNavigation.Content` — the main navigation region. Renders the direct
children of its `root` (as groups) via `NavTree`. Not meant to be used
standalone — rendered internally by `SideNavigation`.
-->

// packages/react/ds-app/src/lib/SideNavigation/common/Content/Content.tsx
import type React from "react";
import { NavTree } from "../NavTree/index.js";
import type { ContentProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds content";

/**
 * SideNavigation.Content — main navigation region. Renders the direct children
 * of its `root` Item via useNavigationTree (selection, active state, keyboard
 * traversal). Falls back to `children` when no `root` is given.
 *
 * @implements ds:apps.subcomponent.side-navigation-content
 */
const Content = ({
  className,
  root,
  LinkComponent = "a",
  currentUrl,
  children,
  ...props
}: ContentProps): React.ReactElement => {
  return (
    <div
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
    >
      {root ? (
        <NavTree
          root={root}
          currentUrl={currentUrl}
          LinkComponent={LinkComponent}
        />
      ) : (
        children
      )}
    </div>
  );
};

export default Content;
