// packages/svelte/ds-app-launchpad/src/lib/components/common/DialogContent/common/Header/Header.svelte
<!-- @canonical/generator-ds 0.10.0-experimental.2 -->

<script lang="ts">
  import type { HeaderProps } from "./types.js";
  import "./styles.css";

  const componentCssClassName = "ds dialog-content-header";

  let { class: className, children, ...rest }: HeaderProps = $props();
</script>

<header class={[componentCssClassName, className]} {...rest}>
  {@render children?.()}
</header>

// packages/react/ds-core/src/ui/Card/common/Header/Header.tsx
/* @canonical/generator-ds 0.10.0-experimental.2 */

import type React from "react";
import type { HeaderProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "header";

/**
 * Header component for Card headers
 */
const Header = ({ className, ...props }: HeaderProps): React.ReactElement => {
  return (
    <header
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      {...props}
    />
  );
};

export default Header;
